### ISSUE TITLE
[BUG] crash au bout de 5 min du bot

### ISSUE THREAD

**Issue by TheFiery** [Ateek2/bot-discord-statut-web-serveur#3]
Bonjour après 5min que j'ai ouvert **start.bat** j'obtiens ceci:

![Capture](https://user-images.githubusercontent.com/78815430/183730792-2a9de9de-aecb-47f3-a158-10815f9affa1.PNG)

**Comment by Ateek2** [comment]
bonjour @TheFiery 

j'ai règle le problème mais je les pas teste re télécharge le index.js cela devrais règle le problème

**Comment by TheFiery** [comment]
![sqfxcvcx](https://user-images.githubusercontent.com/78815430/187093369-41a13710-f269-4f6a-8868-05b9dc12ba6a.JPG)
bonjour désolé j'avais pas vu votre réponse, ça ne fonctionne toujours pas

**Comment by Ateek2** [comment]
problème résolu tout marche bien de mon cote j'ai remis a jour le fichier principale index.js je lest sur un server prive et tous fonctionne bien
